config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :locations, only: [:create, :new]
  resource :friendships, only: [:create, :destroy, :update]
  root 'home#index'
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
  validates :status, presence: true, inclusion: { in: %w(pending declined accepted) }

  scope :accepted, -> { where(status: "accepted") }
  scope :pending, -> { where(status: "pending") }

  def accept
    update_attribute(:status, "accepted")
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user
  has_many :shared_locations

  scope :public_to_all, -> { where(public: true) }

  def shared_locations_with_friends(friend_ids)
    shared_locations.destroy_all

    user.friends.where(id: friend_ids).map do |friend|
      shared_locations.create(friend_id: friend.id, user_id: user.id)
    end

    user.inverse_friends.where(id: friend_ids).map do |friend|
      shared_locations.create(friend_id: friend.id, user_id: user.id)
    end
  end

  def as_json(options = { })
    h = super(options)
    h[:friend_ids] = shared_locations.pluck(:friend_id)
    h
  end
end

app/models/shared_location.rb
class SharedLocation < ActiveRecord::Base
  belongs_to :location
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable

  has_many :friendships
  has_many :friends, -> { where(friendships: { status: "accepted" }) }, through: :friendships

  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, -> { where(friendships: { status: "accepted" }) }, through: :inverse_friendships, source: :user

  has_many :pending_friends, -> { where(friendships: { status: "pending" }) }, through: :friendships, source: :friend
  has_many :requested_friends, -> { where(friendships: { status: "pending" }) }, through: :inverse_friendships, source: :user

  has_many :locations
  has_many :shared_locations
  has_many :inverse_shared_locations, class_name: "SharedLocation", foreign_key: :friend_id

  has_many :shared_locations_by_friends, through: :inverse_shared_locations, source: :location
  has_many :shared_locations_by_me, through: :shared_locations, source: :location

  def mutual_friends
    friends | inverse_friends
  end

  def has_friendship?(user)
    mutual_friends.collect(&:id).include?(user.id)
  end

  def shared_locations(current_user)
    shared_locations_by_friends | shared_locations_by_me
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    friendship = current_user.friendships.build(friend_id: params[:friend_id])

    if friendship.save
      redirect_to users_path, notice: "Added friend."
    else
      redirect_to users_path, error: "Unable to add friend."
    end
  end

  def update
    friendship = current_user.inverse_friendships.find_by(user_id: params[:id])
    if friendship.accept
      redirect_to request.referrer, notice: "Friendship accepted"
    else
      redirect_to request.referrer, notice: "Some thing went wrong"
    end
  end

  def destroy
    friendship = Friendship.where(user_id: [current_user, params[:id]]).where(friend_id: [current_user, params[:id]]).last
    friendship.destroy
    redirect_to request.referrer, notice: "Removed friendship."
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.public_to_all.limit(10)
    @locations = @locations.to_json(include: :user)
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = current_user
    location = @user.locations.find(params[:location].delete(:id)) if params[:location][:id].present?
    location ||= @user.locations.build

    if location.update_attributes(location_params)
      location.shared_locations_with_friends(params[:friend_ids]) if params[:friend_ids]
      @locations = current_user.locations.to_json(include: :user)
      render layout: false
    end
  end

  private

  def location_params
    params.require(:location).permit(:latitude, :longitude, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where.not(id: current_user.id).all
    @pending_friend_ids = current_user.pending_friends.pluck(:friend_id)
    @requested_friend_ids = current_user.requested_friends.pluck(:user_id)
  end

  def show
    @user = User.find_by_username(params[:id])

    if current_user == @user
      @locations = @user.locations
    else
      @locations = @user.locations.public_to_all
    end

    @locations = @locations | @user.shared_locations(current_user)
    @locations = @locations.to_json(include: :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="map" class="map"></div>
<% content_for(:javascript) do %>
  OpenLayer.init(JSON.parse("<%= j raw(@locations) %>"), null, null);
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <li><%= link_to "Find Friends", users_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.email %> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", user_path(current_user.username) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: "Delete" %></li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Log in", "/users/sign_in" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareLocation</title>
  <link rel="stylesheet" href="https://openlayers.org/en/v4.5.0/css/ol.css" type="text/css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <script src="https://openlayers.org/en/v4.5.0/build/ol.js" type="text/javascript"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/navbar" %>
  <div class="container">
    <%= yield %>
    <%= javascript_tag do %>
      <%= yield :javascript %>
    <% end %>
  </div>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for Location.new, url: locations_path, method: "POST", remote: true, html: { class: "form-horizontal" } do |f| %>
  <%= f.hidden_field :id %>

  <div class="form-group">
    <%= f.label :latitude, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :latitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :longitude, class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :longitude, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-6">
      <div class="checkbox">
        <label>
          <%= f.check_box :public %> Publish this location
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= label_tag :friend, "Share this location with friends", class: "col-sm-4 control-label" %>
    <div class="col-sm-6">
      <%= collection_select nil, :friend_ids, @user.mutual_friends, :id, :username, { include_blank: 'Select' }, { id: "location-friend-ids", multiple: true, class: "form-control" } %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-6">
      <%= f.submit "Save", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/locations/create.js.erb
$(".map-container").html("<%= j render 'users/map' %>");
OpenLayer.init(JSON.parse("<%= j raw(@locations) %>"), "<%= current_user.id %>", "<%= @user.id %>");

app/views/locations/new.html.erb
<%= render "form" %>

app/views/users/_map.html.erb
<div id="map" class="map col-md-8"></div>
<% if current_user == @user %>
  <div class="col-md-4 location-form-container">
    <%= render "locations/form" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user.username, user_path(user.username) %></td>
              <td><%= user.email %></td>
              <td>
                <% if current_user.has_friendship?(user) %>
                  <%= link_to "Remove Friendship", friendships_path(id: user), method: "DELETE", class: "btn btn-default pull-right" %>
                <% elsif @requested_friend_ids.include?(user.id) %>
                  <%= link_to "Accept", friendships_path(id: user), method: "PUT", class: "btn btn-success pull-right" %>
                  <%= link_to "Reject", friendships_path(id: user), method: "DELETE", class: "btn btn-danger pull-right" %>
                <% elsif @pending_friend_ids.include?(user.id) %>
                  <span class="btn btn-primary pull-right" disabled="disabled">Request Sent</span>
                <% else %>
                  <%= link_to "Send Friend Request", friendships_path(friend_id: user), method: "POST", class: "btn btn-primary pull-right" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row border-bottom">
    <h4 class="pull-left"><%= @user.email %></h4>
    <% unless current_user == @user || current_user.has_friendship?(@user) %>
    <%= link_to "Add Friend", friendships_path(friend_id: @user), method: "POST", class: "pull-right btn btn-primary" %>
    <% end %>
  </div>
  <div class="row border-bottom map-container">
    <%= render "map" %>
  </div>

  <div class="row">
    <h3>Friends</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @user.mutual_friends.each do |friend| %>
          <tr>
            <td><%= link_to friend.username, user_path(friend.username) %></td>
            <td><%= friend.email %></td>
            <% if current_user == @user %>
              <td><%= link_to "Remove", friendships_path(:id => friend), :method => "DELETE", class: "pull-right btn btn-danger" %>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <% if current_user == @user %>
    <div class="row">
      <h3>Friend Requests</h3>
      <div class="column">
        <table class="table">
          <tbody>
            <% @user.requested_friends.each do |request| %>
            <tr>
              <td><%= link_to request.username, user_path(request.username) %></td>
              <td><%= request.email %></td>
              <td>
                <%= link_to "Accept", friendships_path(:id => request), :method => "PUT", class: "pull-right btn btn-success" %>
                <%= link_to "Decline", friendships_path(:id => request), :method => "DELETE", class: "pull-right btn btn-danger" %>
              </td>
             </tr>
            <% end %>
            <% @user.pending_friends.each do |friend| %>
            <tr>
              <td><%= link_to friend.username, user_path(friend.username) %></td>
              <td><%= friend.email %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  <% end %>
</div>
<% content_for(:javascript) do %>
  OpenLayer.init(JSON.parse("<%= j raw(@locations) %>"), "<%= current_user.id %>", "<%= @user.id %>");
<% end %>